name: CI/CD pipeline

on: 
  push:
    branches:
      - main
      - '**'  # Run on every branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Echo secret keys (for debugging - remove in production)
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "REDIS_HOST=${REDIS_HOST}"
          echo "REDIS_PORT=${REDIS_PORT}"
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}"
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}"

      - name: Run tests with pytest
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest --maxfail=1 --disable-warnings -v 
